version: 2.1
jobs:
  test:
    docker:
        #imagen que vamos a utilizar
      - image: josemip98/organizeudiet
    #listado de órdenes para ejecutar
    steps:
      - checkout
          #norden para ver errores
      - run:
          name: Lanzar tests
          #ejecutamos los tests con el gestor de tareas gulp
          command: |
            gulp test
#flujos de trabajo
workflows:
  testeo:
    jobs:
      #tarea a ejecutar
      - test
