#versión de la plataforma circle que estamos usando
version: 2.1
#tareas que vamos a realizar
jobs:
  #nombre de la tarea
  test:
    docker:
        #imagen que vamos a usar, en este caso necesitamos node
      - image: josemip98/organizeudiet
    #listado de órdenes a ejecutar
    steps:
      - checkout
          #nombre proporcionado para dirigirnos a esta orden a la hora de ver errores o warnings
      - run:
          name: Lanzar tests
          #ejecutamos los tests con el gestor de tareas
          command: |
            gulp test
#flujos de trabajo
workflows:
  testeo:
    jobs:
      #tarea a ejecutar
      - test
